name: CI
on: 
  push:
    paths-ignore: 
      - '**.md'

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.17', '1.18', '1.19']
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Setup Go - ${{ matrix.go-version }}
        uses: actions/setup-go@v3.3.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go version
        run: go version

      - run: go test -v